### ISSUE TITLE
Set-PlaylistItems not working as expected with more than 100 tracks

### ISSUE THREAD

**Issue by bcruvelier** [wardbox/spotishell#39]
**Describe the bug**
When using Set-PlaylistItems with more than 100 tracks to add, the playlist only contains the last batch. 

**To Reproduce**
1. Create a playlist
2. Add 120 tracks with Set-PlaylistItems
3. Only 20 tracks will be on the playlist

**Expected behavior**
All tracks should be in the playlist

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Powershell Version : 5.1

**Comment by bcruvelier** [comment]
I think the problem comes from the fact that you do a PUT for every 100 tracks, so the playlist is reset everytime you called the method. 
Maybe you could do a first PUT to reset the playlist and then do a POST with Add-PlaylistItem for the other tracks to add ?

**Comment by Domochip** [comment]
Hello,

Could you check that this commit fixes the issue : 
https://github.com/Domochip/spotishell/commit/922a1342b04e823c763f198952f23cd4b5c5f18a

thx

**Comment by Domochip** [comment]
up

**Comment by Domochip** [comment]
:-) The question was for @bcruvelier
I didn't tested it myself
Did you?

**Comment by wardbox** [comment]
ahhh i see, i didn't try it out myself

**Comment by Domochip** [comment]
I tested it and the PR40 solve the issue
