### ISSUE TITLE
Set-ShufflePlayback Not working

### ISSUE THREAD

**Issue by sandersoncw55** [wardbox/spotishell#47]
First of all, amazing work on this module! I found one small easy to fix bug.

In the function for Set-ShufflePlayback you are attempting to convert a Boolean to lower. Need to convert System.Boolean to string then convert to lower. 
Example Fix:
    $Uri = 'https://api.spotify.com/v1/me/player/shuffle?state=' + $State.ToString().ToLower()

**Comment by Domochip** [comment]
Thanks, I've created a PR to fix that :-)

**Comment by Domochip** [comment]
@sandersoncw55 Could you give it a try?
